# Makefile automatically generated by ghdl
# Version: GHDL 0.36-dev (20181129-164-gb324bb6) [Dunoon edition] - mcode code generator
# Command used to generate this makefile:
# ghdl --gen-makefile counter_block_tb --vcd=tb.vcd

GHDL=ghdl
GHDLFLAGS=
GHDLRUNFLAGS= --vcd=tb.vcd

# Default target : elaborate
all : elab

# Elaborate target.  Almost useless
elab : force
	$(GHDL) -c $(GHDLFLAGS) -e counter_block_tb

# Run target
run : force
	$(GHDL) -c $(GHDLFLAGS) -r counter_block_tb $(GHDLRUNFLAGS)

# Targets to analyze libraries
init: force
	# /usr/local/lib/ghdl/ieee/v93/../../src/ieee/std_logic_1164.v93
	# /usr/local/lib/ghdl/ieee/v93/../../src/ieee/std_logic_1164_body.v93
	# /usr/local/lib/ghdl/ieee/v93/../../src/ieee/numeric_std.v93
	# /usr/local/lib/ghdl/ieee/v93/../../src/ieee/numeric_std-body.v93
	$(GHDL) -a $(GHDLFLAGS) counter_block.vhd
	$(GHDL) -a $(GHDLFLAGS) counter_block_tb.vhd

force:
